version: "3"
services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - ./torch_transformer:/app/torch_transformer
      - ./main.py:/app/main.py
    ports:
      - "8501:8501"
    command:
      - streamlit
      - run
      - main.py
